/**
 * Represents a user-generated asset, which can be a character or an environment.
 */
export interface IAsset {
  id: string
  name: string
  type: 'character' | 'environment'
  prompt: string // This should be the user-editable part of the prompt
  imageUrl?: string // URL to the generated image
  history?: IImageHistory[]
  selectedHistoryId?: string
  referenceImage?: string | null
}

/**
 * Represents a single generation/finetuning instance of an image.
 */
export interface IImageHistory {
  id: string
  imageUrl: string
  prompt: string
  createdAt: string
}

/**
 * Represents a single panel within a manga page.
 */
export interface IPanel {
  id: string
  panelNumber: number
  prompt: string
  imageUrl?: string // URL to the generated panel image
  history?: IImageHistory[]
  selectedHistoryId?: string
  referenceImage?: string | null
}

/**
 * Represents a single generated manga page, which consists of multiple panels.
 */
export interface IMangaPage {
  id: string
  pageNumber: number
  summary: string // The overall plan/summary for this page
  panels: IPanel[]
  isGenerated: boolean
  finalImageUrl?: string // The composite image of the entire page
  history?: IImageHistory[]
  selectedHistoryId?: string
  referenceImage?: string | null
}

/**
 * Represents a high-level plan for the entire manga story, generated by AI.
 */
export interface IStoryPlan {
  detailedStorySummary: string
  detailedArtStyle: string
  characters: {
    name: string
    description: string
  }[]
  environments: {
    name: string
    description: string
  }[]
  pages: {
    page: number
    description: string // This will now be a more detailed plot point
  }[]
}

/**
 * Represents the entire state of a single manga project.
 * This is the structure that will be saved and loaded.
 */
export interface IProjectState {
  // From StoryFoundation
  genre: string
  colorStyle: string
  storySummary: string
  artStyle: string
  artStyleImage?: string | null

  // From StoryPlanner
  storyPlan: IStoryPlan | null

  // From AssetCreator
  characters: IAsset[]
  environments: IAsset[]

  // From PageGenerator & MangaContext
  pages: IMangaPage[]

  // From GenerationSettings
  aspectRatio: string
  resolution: string
  textModel?: string
  imageModel?: string

  // Metadata
  version: string
  createdAt: string
}
