'use client'

import { useState } from 'react'
import { useTranslations } from 'next-intl'
import { useStudio } from '@/components/studio-context'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { CharacterCreator } from '@/components/character-creator'
import { EnvironmentCreator } from '@/components/environment-creator'
import { PhotoshootStudio } from '@/components/photoshoot-studio'
import { AssetList } from '@/components/asset-list'
import {
  IAsset,
  IStudioProject,
  ICharacterAsset,
  IEnvironmentAsset,
  IPhoto,
} from '@/types'
import { Header } from '@/components/header'
import { IPersonAppearance } from '@/types'

const EMPTY_PERSON_APPEARANCE: IPersonAppearance = {
  person_appearance: {
    basic_info: { name: '', perceived_age: '', gender: 'Other', ethnicity: '' },
    body: { height: { value: 0, unit: 'cm' }, build: '' },
    head_and_face: {
      face_shape: '',
      skin: { tone: '' },
      hair: { color: '', length: '', style: '' },
      eyes: { color: '', shape: '' },
    },
    clothing_and_accessories: { style_vibe: '' },
    expression_and_mood: { primary_emotion: '' },
  },
}

export default function ProjectPage() {
  const t = useTranslations('Index')
  const t_assetCreator = useTranslations('AssetCreator')
  const t_assetList = useTranslations('AssetList')

  const {
    characters,
    environments,
    photos,
    artStyle,
    artStyleImage,
    aspectRatio,
    resolution,
    textModel,
    imageModel,
    version,
    createdAt,
    updateCharacter,
    addCharacter,
    deleteCharacter,
    addEnvironment,
    updateEnvironment,
    deleteEnvironment,
    setProject,
  } = useStudio()

  const [selectedAsset, setSelectedAsset] = useState<IAsset | null>(null)
  const [isSettingsModalOpen, setIsSettingsModalOpen] = useState(false)
  const [leftColumnView, setLeftColumnView] = useState<
    'asset-lists' | 'editor'
  >('asset-lists')

  const handleCreateNewAsset = (type: 'character' | 'environment') => {
    if (type === 'character') {
      // Create a minimal character asset shell to trigger the editor in 'new' mode
      const newCharacter: ICharacterAsset = {
        id: '', // ID will be generated by the editor/context
        name: '',
        type: 'character',
        descriptor: EMPTY_PERSON_APPEARANCE,
      }
      setSelectedAsset(newCharacter)
    } else {
      // Create a minimal environment asset shell
      const newEnvironment: IEnvironmentAsset = {
        id: '',
        name: '',
        type: 'environment',
        prompt: '',
      }
      setSelectedAsset(newEnvironment)
    }
    setLeftColumnView('editor')
  }

  const handleAssetSelection = (asset: IAsset) => {
    setSelectedAsset(asset)
    setLeftColumnView('editor')
  }

  const handleAssetCreated = (asset: IAsset) => {
    let isExisting = false
    if (asset.type === 'character') {
      isExisting = characters.some((c) => c.id === asset.id)
      if (isExisting) {
        updateCharacter(asset as ICharacterAsset)
      } else {
        addCharacter(asset as ICharacterAsset)
      }
    } else {
      isExisting = environments.some((e) => e.id === asset.id)
      if (isExisting) {
        updateEnvironment(asset as IEnvironmentAsset)
      } else {
        addEnvironment(asset as IEnvironmentAsset)
      }
    }

    // Only go back to the list if it's a new asset
    if (!isExisting) {
      setSelectedAsset(null)
      setLeftColumnView('asset-lists')
    } else {
      // If it's an existing asset, just update the state for the editor
      setSelectedAsset(asset)
    }
  }

  const handleDeleteAsset = (assetId: string) => {
    deleteCharacter(assetId)
    deleteEnvironment(assetId)
  }

  const handleUpdateAsset = (asset: IAsset) => {
    if (asset.type === 'character') {
      updateCharacter(asset as ICharacterAsset)
    } else {
      updateEnvironment(asset as IEnvironmentAsset)
    }
    if (selectedAsset && selectedAsset.id === asset.id) {
      setSelectedAsset(asset)
    }
  }

  // TODO: Re-implement save/load logic with the new project structure
  const gatherProjectState = (): IStudioProject => {
    return {
      characters,
      environments,
      photos,
      artStyle,
      artStyleImage,
      aspectRatio,
      resolution,
      textModel,
      imageModel,
      version,
      createdAt,
    }
  }

  const restoreProjectState = (newState: IStudioProject) => {
    console.log('Restoring state:', newState)
    setProject(newState)
  }

  return (
    <div className="flex flex-col gap-8">
      <Header
        gatherProjectState={gatherProjectState}
        restoreProjectState={restoreProjectState}
      />

      <div className="grid grid-cols-1 lg:grid-cols-[480px_1fr] gap-8 items-start">
        {/* Left Column: Asset Management */}
        <div className="lg:col-span-1 flex flex-col gap-8">
          {leftColumnView === 'asset-lists' && (
            <>
              <Card>
                <CardHeader>
                  <CardTitle>{t_assetList('characters')}</CardTitle>
                </CardHeader>
                <CardContent>
                  <AssetList
                    assets={characters}
                    selectedAssetName={selectedAsset?.name}
                    onAssetClick={handleAssetSelection}
                    onUpdateAsset={handleUpdateAsset}
                    onDeleteAsset={handleDeleteAsset}
                    aspectRatio={aspectRatio}
                    resolution={resolution}
                  />
                  <Button
                    onClick={() => handleCreateNewAsset('character')}
                    className="w-full mt-4"
                  >
                    {t('newCharacter')}
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>{t_assetList('environments')}</CardTitle>
                </CardHeader>
                <CardContent>
                  <AssetList
                    assets={environments}
                    selectedAssetName={selectedAsset?.name}
                    onAssetClick={handleAssetSelection}
                    onUpdateAsset={handleUpdateAsset}
                    onDeleteAsset={handleDeleteAsset}
                    aspectRatio={aspectRatio}
                    resolution={resolution}
                  />
                  <Button
                    onClick={() => handleCreateNewAsset('environment')}
                    className="w-full mt-4"
                  >
                    {t('newEnvironment')}
                  </Button>
                </CardContent>
              </Card>
            </>
          )}

          {leftColumnView === 'editor' && selectedAsset && (
            <Card>
              <CardHeader>
                <Button
                  variant="outline"
                  onClick={() => setLeftColumnView('asset-lists')}
                >
                  &larr; {t('backToList')}
                </Button>
              </CardHeader>
              <CardContent>
                {selectedAsset?.type === 'character' && (
                  <CharacterCreator
                    onAssetCreated={handleAssetCreated}
                    existingAsset={selectedAsset as ICharacterAsset}
                  />
                )}
                {selectedAsset?.type === 'environment' && (
                  <EnvironmentCreator
                    onAssetCreated={handleAssetCreated}
                    existingAsset={selectedAsset as IEnvironmentAsset}
                  />
                )}
              </CardContent>
            </Card>
          )}
        </div>

        {/* Right Column: Photoshoot Studio */}
        <div className="lg:col-span-1">
          <PhotoshootStudio />
        </div>
      </div>
    </div>
  )
}
